"use client";

import { useEffect, useState } from "react";
import { APIError } from "../../../lib/api/client";
import { getCurrentUser } from "../../../lib/api/auth";
import { createAgent, getAgentCredentialMigrationStatus, listAgents, revokeAgentKey, rotateAgentKey } from "../../../lib/api/agents";
import type { CredentialMigrationStatus } from "../../../lib/api/agents";
import type { Agent, CurrentUser } from "../../../lib/api/types";
import { hasPermission } from "../../../lib/permissions";

const writePermission = "agent:write";
function errorMessage(error: unknown): string { return error instanceof APIError ? error.message : "Request failed. Please retry."; }

export default function AgentsPage() {
  const [agents, setAgents] = useState<Agent[]>([]); const [user, setUser] = useState<CurrentUser | null>(null);
  const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  const [migration, setMigration] = useState<CredentialMigrationStatus | null>(null); const [migrationError, setMigrationError] = useState<string | null>(null);
  const [migrationQuery, setMigrationQuery] = useState(""); const [migrationLoading, setMigrationLoading] = useState(false);
  const [newCredential, setNewCredential] = useState<{ api_key: string; signing_secret: string } | null>(null); const [name, setName] = useState("");
  const canWrite = hasPermission(user, writePermission);
  async function loadMigrationStatus(query = migrationQuery) { setMigrationLoading(true); setMigrationError(null); try { setMigration(await getAgentCredentialMigrationStatus({ page: 1, page_size: 20, q: query })); } catch (err) { setMigrationError(errorMessage(err)); } finally { setMigrationLoading(false); } }
  useEffect(() => { Promise.all([getCurrentUser(), listAgents()]).then(([currentUser, list]) => { setUser(currentUser); setAgents(list); }).catch((err) => setError(errorMessage(err))); void loadMigrationStatus(""); }, []);
  async function create() { if (!canWrite || !name.trim()) return; setBusy("create"); setError(null); try { const result = await createAgent({ name, description: "", environment: "production" }); setAgents((current) => [result.agent, ...current]); setNewCredential({ api_key: result.api_key, signing_secret: result.signing_secret }); setName(""); } catch (err) { setError(errorMessage(err)); } finally { setBusy(null); } }
  async function rotate(agent: { id: string }) { if (!canWrite) return; setBusy(agent.id); setError(null); try { const result = await rotateAgentKey(agent.id); setNewCredential({ api_key: result.api_key, signing_secret: result.signing_secret }); await loadMigrationStatus(); } catch (err) { setError(errorMessage(err)); } finally { setBusy(null); } }
  async function revoke(agent: Agent) { if (!canWrite) return; setBusy(agent.id); setError(null); try { await revokeAgentKey(agent.id); setAgents((current) => current.map((item) => item.id === agent.id ? { ...item, status: "credential_revoked" } : item)); } catch (err) { setError(errorMessage(err)); } finally { setBusy(null); } }
  return <section><h1 className="page-title">Agents</h1><p className="page-description">Manage production Agent identities and credentials.</p>{user && <p role="status">Signed in as <strong>{user.role}</strong>. {canWrite ? "You can manage credentials." : "Read-only access."}</p>}{error && <div role="alert" className="error-banner">{error}</div>}{migrationError && <div role="alert" className="error-banner">Credential migration status unavailable: {migrationError}</div>}{migration && <div className="panel" role="status"><strong>{migration.summary.legacy_agents === 0 ? "All active Agents are HMAC-ready." : `${migration.summary.legacy_agents} active Agent(s) still require credential rotation before HMAC enforcement.`}</strong><p>Migrated {migration.summary.migrated_agents} of {migration.summary.total_agents} active Agents.</p><div><input aria-label="Search legacy agents" placeholder="Search legacy Agents" value={migrationQuery} onChange={(e) => setMigrationQuery(e.target.value)} /><button disabled={migrationLoading} onClick={() => void loadMigrationStatus()}>{migrationLoading ? "Loading…" : "Refresh migration status"}</button></div>{migration.summary.legacy_agents > 0 && <table className="trace-table"><thead><tr><th>Legacy Agent</th><th>Environment</th><th>Last used</th>{canWrite && <th>Action</th>}</tr></thead><tbody>{migration.agents.map((legacy) => <tr key={legacy.id}><td>{legacy.name}</td><td>{legacy.environment}</td><td>{legacy.last_used_at ? new Date(legacy.last_used_at).toLocaleString() : "Never"}</td>{canWrite && <td><button disabled={busy === legacy.id} onClick={() => void rotate({ id: legacy.id })}>Rotate key</button></td>}</tr>)}</tbody></table>}</div>}{canWrite && <div className="panel agent-form"><input aria-label="Agent name" placeholder="Agent name" value={name} onChange={(e) => setName(e.target.value)} /><button disabled={busy === "create"} onClick={create}>{busy === "create" ? "Creating…" : "Create Agent"}</button></div>}{newCredential && <div role="alert" className="key-reveal"><strong>Save these credentials now. They will not be shown again:</strong><p>API key</p><code>{newCredential.api_key}</code><p>Signing secret</p><code>{newCredential.signing_secret}</code><button onClick={() => setNewCredential(null)}>Hide</button></div>}<div className="panel"><table className="trace-table"><thead><tr><th>Name</th><th>Environment</th><th>Status</th>{canWrite && <th>Actions</th>}</tr></thead><tbody>{agents.map((agent) => <tr key={agent.id}><td>{agent.name}</td><td>{agent.environment}</td><td>{agent.status}</td>{canWrite && <td><button disabled={busy === agent.id} onClick={() => rotate(agent)}>Rotate key</button> <button disabled={busy === agent.id} onClick={() => revoke(agent)}>Revoke key</button></td>}</tr>)}</tbody></table></div></section>;
}
